CREATE VIEW SHOW_ALL_RESPONSES
AS
(
SELECT S.SURVEY_NAME
,R.NAME
,CONCAT(QUESTION1, ' : ', R.RESPONSE1) AS "RESPONSE1"
,CONCAT(QUESTION2, ' : ', R.RESPONSE2) AS "RESPONSE2"
,CONCAT(QUESTION3, ' : ', R.RESPONSE3) AS "RESPONSE3"
,CONCAT(QUESTION4, ' : ', R.RESPONSE4) AS "RESPONSE4"
,CONCAT(QUESTION5, ' : ', R.RESPONSE5) AS "RESPONSE5"
FROM SURVEY S
INNER JOIN USER_RESPONSES R ON S.SID=R.SID
INNER JOIN Q1 ON S.SID=Q1.SID
INNER JOIN Q2 ON S.SID=Q2.SID
INNER JOIN Q3 ON S.SID=Q3.SID
INNER JOIN Q4 ON S.SID=Q4.SID
INNER JOIN Q5 ON S.SID=Q5.SID
);