CREATE VIEW SHOW_ALL_SURVEYS
AS
(
SELECT S.SURVEY_NAME
,QUESTION1
,QUESTION2
,QUESTION3
,QUESTION4
,QUESTION5
FROM SURVEY S INNER JOIN Q1 ON S.SID=Q1.SID
INNER JOIN Q2 ON S.SID=Q2.SID
INNER JOIN Q3 ON S.SID=Q3.SID
INNER JOIN Q4 ON S.SID=Q4.SID
INNER JOIN Q5 ON S.SID=Q5.SID
);